/**
 * The normalized, adapter-agnostic Session model.
 *
 * Every adapter (Claude Code today; others later) maps its native transcript into this shape.
 * The analyzer and the report only ever read this model, never raw records.
 *
 * Conventions:
 * - all times are epoch milliseconds (number) or undefined when unknown
 * - token counts are raw integers as reported by the provider
 * - `agentId` is undefined for the main thread and set for subagent/sidechain activity
 * - nothing here is required to be present: parsers fill what they can and record gaps in `parseReport`
 */

export type SourceKind = 'claude-code' | 'unknown'

export interface SessionMeta {
  sessionId: string
  source: SourceKind
  /** absolute path of the main transcript file */
  path: string
  /** paths of subagent transcripts that were merged in */
  subagentPaths: string[]
  projectSlug?: string
  cwd?: string
  gitBranches: string[]
  /** distinct client versions seen (e.g. Claude Code "2.1.226") */
  clientVersions: string[]
  entrypoints: string[]
  /** custom title (/rename) if any, else first user prompt preview */
  title?: string
  customTitle?: string
  /** title generated by Claude Code itself (ai-title record) */
  aiTitle?: string
  agentName?: string
  relocatedCwd?: string
  worktree?: boolean
  startedAt?: number
  endedAt?: number
  /** wall clock from first to last record */
  wallMs?: number
  permissionModes: string[]
  models: string[]
  effortLevels: string[]
  /** true when the file looks like it is still being appended to (partial last line or very recent mtime) */
  possiblyLive: boolean
  /** skills listed as available at session start (from the skill_listing attachment) */
  skillsAvailable?: { count: number; names: string[] }
  /** number of Read results Claude Code truncated (read_truncation_notice) */
  truncatedReads: number
  /** queue-operation record counts by operation (enqueue / dequeue / remove / popAll) */
  queueOperations?: Record<string, number>
  /**
   * enqueue records split by content (additive: human + notification = queueOperations.enqueue).
   * `notification` = machine-generated envelopes (`<task-notification>` / `<system-notification>`);
   * `human` = everything else: typed prompts and agent/cross-session messages.
   */
  enqueueKinds?: { human: number; notification: number }
  /** deferred tool names announced by deferred_tools_delta attachments (sorted, unique) */
  deferredToolNames?: string[]
}

/** why an API call missed the prompt cache (message.diagnostics.cache_miss_reason) */
export interface CacheMissReason {
  /** messages_changed | previous_message_not_found | unavailable | tools_changed | system_changed | model_changed */
  type: string
  /** cache_missed_input_tokens when reported: tokens re-written because of the miss */
  missedInputTokens?: number
}

export type BlockKind = 'text' | 'thinking' | 'redacted_thinking' | 'tool_use' | 'tool_result' | 'image' | 'document' | 'other'

export interface TextBlock {
  kind: 'text'
  text: string
}
export interface ThinkingBlock {
  kind: 'thinking'
  /** characters of thinking; the text itself is kept for the explorer but may be redacted */
  chars: number
  text?: string
}
export interface ToolUseBlock {
  kind: 'tool_use'
  toolUseId: string
  name: string
  input: unknown
}
export interface ToolResultBlock {
  kind: 'tool_result'
  toolUseId: string
  /** the textual content (joined) when available */
  text: string
  isError: boolean
  /** bytes of the serialized content */
  bytes: number
}
export interface OtherBlock {
  kind: 'image' | 'document' | 'redacted_thinking' | 'other'
  rawType?: string
  bytes: number
  /** human note for special blocks (e.g. model fallback) */
  note?: string
}
export type Block = TextBlock | ThinkingBlock | ToolUseBlock | ToolResultBlock | OtherBlock

export type MessageRole = 'user' | 'assistant' | 'system'

/**
 * How a user-role message came to be:
 * - human: typed by the person
 * - command: a slash command typed by the person (<command-name>)
 * - peer: a message from another session/agent (teammate / cross-session)
 * - scheduled: a timer / loop wake-up injected by the client
 * - notification: background task / subagent completion notice
 * - local_output: output of a local slash command
 * - interrupt: "[Request interrupted by user]"
 * - meta: injected context (system reminders, session naming, etc.)
 */
export type PromptKind = 'human' | 'command' | 'peer' | 'scheduled' | 'notification' | 'local_output' | 'interrupt' | 'meta'
export const TURN_STARTING_KINDS: ReadonlySet<PromptKind> = new Set<PromptKind>(['human', 'command', 'peer', 'scheduled'])

export interface Usage {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  cacheWrite5m: number
  cacheWrite1h: number
  webSearchRequests: number
  webFetchRequests: number
  serviceTier?: string
  /** 'fast' triggers fast-mode base rates on supported models; default 'standard' */
  speed?: string
  /** inference geo tier ('us' costs 1.1x on 4.6+ models); usually 'not_available' */
  inferenceGeo?: string
}

export interface Message {
  /** transcript-level uuid */
  uuid: string
  parentUuid?: string
  role: MessageRole
  /** epoch ms */
  ts?: number
  /** index of the turn this message belongs to (main thread), or the sub-turn inside an agent run */
  turnIndex: number
  agentId?: string
  isSidechain: boolean
  /** Claude Code marks injected/meta user messages (system reminders, command outputs) */
  isMeta: boolean
  isCompactSummary: boolean
  /** true when the user content is a tool_result carrier rather than a human prompt */
  isToolResultCarrier: boolean
  /** true when this user message starts a turn (human-typed, slash command, peer message, or scheduled wake) */
  isHumanPrompt: boolean
  /** classification of a user (non tool_result) message */
  promptKind?: PromptKind
  blocks: Block[]
  /** assistant-only */
  model?: string
  effort?: string
  requestId?: string
  /** provider message id (shared across streamed chunks of the same response) */
  providerMessageId?: string
  stopReason?: string
  usage?: Usage
  /** whether this record's usage was counted (false for duplicate chunks of the same provider message) */
  usageCounted: boolean
  /** short preview of the text content, for lists */
  preview: string
  /** original 1-based line in the source file */
  line?: number
  /** which file it came from (index into meta.path + subagentPaths) */
  fileIndex: number
  /** system subtype or slash-command marker when applicable */
  systemSubtype?: string
  /** slash command name when the user message carries <command-name> */
  commandName?: string
  /** true when the message text contains "[Request interrupted by user" */
  interrupted: boolean
  /** api error info when this assistant record is an error message */
  apiError?: { status?: number | string; message?: string }
  /** Claude Code attribution of this assistant step to a skill / plugin / MCP server (when present) */
  attribution?: { skill?: string; plugin?: string; mcpServer?: string; mcpTool?: string; agent?: string }
  /** thinking tokens billed inside output (usage.output_tokens_details.thinking_tokens; present from CC 2.1.228) */
  thinkingTokens?: number
  /** set when the API reported why the prompt cache missed for this call */
  cacheMissReason?: CacheMissReason
}

export type ToolCategory = 'read' | 'search' | 'edit' | 'write' | 'exec' | 'agent' | 'skill' | 'web' | 'plan' | 'ask' | 'mcp' | 'task' | 'notebook' | 'other'

export interface ToolCall {
  toolUseId: string
  name: string
  category: ToolCategory
  input: unknown
  /** compact human summary of the input, e.g. "Read src/foo.ts" */
  inputSummary: string
  inputBytes: number
  /** the assistant message that issued it */
  messageUuid: string
  turnIndex: number
  agentId?: string
  /** epoch ms of the tool_use message */
  startTs?: number
  /** epoch ms of the tool_result carrier message */
  endTs?: number
  durationMs?: number
  resultBytes?: number
  isError: boolean
  /** true when no result was ever recorded (interrupted / still running) */
  unresolved: boolean
  /** number of sibling tool_use blocks in the same assistant message (1 = sequential) */
  parallelGroupSize: number
  /** structured result payload (Claude Code `toolUseResult`) when present */
  resultMeta?: unknown
  /** for Agent tool calls: the spawned agent id when known */
  spawnedAgentId?: string
  /** for Skill tool calls: the skill name */
  skillName?: string
  /** first ~200 chars of the result text */
  resultPreview?: string
  /** exit code / error hint when derivable */
  errorHint?: string
  /** true when Claude Code truncated the result at the token cap (toolUseResult.file.truncatedByTokenCap) */
  truncated?: boolean
}

export interface AgentRun {
  agentId: string
  /** e.g. code-reviewer, Explore, general-purpose, or a workflow agent label */
  agentType?: string
  name?: string
  description?: string
  model?: string
  spawnDepth: number
  /** the tool_use id of the Agent call that spawned it (main thread) */
  spawnedByToolUseId?: string
  parentAgentId?: string
  transcriptPath?: string
  teamName?: string
  taskKind?: string
  startTs?: number
  endTs?: number
  durationMs?: number
  messageCount: number
  toolCallCount: number
  usage: Usage
  /** as reported by the parent's toolUseResult (may differ from the summed transcript) */
  reportedTotalTokens?: number
  reportedDurationMs?: number
  status?: string
}

export interface SkillInvocation {
  name: string
  /** 'tool' = via the Skill tool, 'command' = a slash command marker in a user message */
  via: 'tool' | 'command'
  turnIndex: number
  ts?: number
  agentId?: string
  args?: string
}

export interface HookRun {
  hookEvent?: string
  hookName?: string
  command?: string
  durationMs?: number
  ok: boolean
  ts?: number
  turnIndex: number
}

export interface CompactionEvent {
  ts?: number
  turnIndex: number
  /** 'auto' | 'manual' | 'unknown' */
  trigger: string
  /** context size just before, when derivable (compactMetadata.preTokens) */
  contextBefore?: number
  /** compactMetadata.postTokens */
  contextAfter?: number
  summaryChars?: number
  /** how long the compaction took (compactMetadata.durationMs) */
  durationMs?: number
  cumulativeDroppedTokens?: number
}

export interface UsageEvent {
  messageUuid: string
  ts?: number
  turnIndex: number
  agentId?: string
  model: string
  effort?: string
  attribution?: Message['attribution']
  usage: Usage
  /** input + cacheRead + cacheWrite = the prompt size the model saw */
  contextSize: number
  /** set for hidden earlier attempts (e.g. a refused first try before a model fallback); billed but not visible as a message */
  hiddenIteration?: { index: number; type?: string }
  /** thinking tokens inside this event's output, when the client reported them */
  thinkingTokens?: number
  /** set when the API reported why the prompt cache missed for this call */
  cacheMissReason?: CacheMissReason
}

export interface Turn {
  index: number
  /** what started the turn */
  kind: PromptKind
  /** epoch ms of the human prompt */
  startTs?: number
  /** epoch ms of the last record before the next human prompt */
  endTs?: number
  durationMs?: number
  /** as reported by Claude Code's turn_duration system record when present */
  reportedDurationMs?: number
  promptPreview: string
  promptChars: number
  commandName?: string
  /** ms from prompt to first assistant record */
  firstResponseMs?: number
  messageUuids: string[]
  toolCallIds: string[]
  agentIds: string[]
  usage: Usage
  models: string[]
  /** true when the prompt is a slash command rather than typed text */
  isCommand: boolean
  interrupted: boolean
  /** number of injected continuations (task notifications, local outputs) inside this turn */
  autoContinuations: number
  /** ms the human spent before this turn (gap since previous turn ended) */
  humanGapMs?: number
}

export interface ParseWarning {
  code: string
  message: string
  count: number
  sampleLine?: number
}

export interface ParseReport {
  totalLines: number
  badLines: number
  recordCounts: Record<string, number>
  unknownRecordTypes: Record<string, number>
  unknownBlockTypes: Record<string, number>
  /** attachment.type counts (hook_success, skill_listing, read_truncation_notice, ...) */
  attachmentTypes: Record<string, number>
  /** serialized payload bytes by attachment.type (additive; absent on analyses from older engines) */
  attachmentBytes?: Record<string, number>
  /** system subtype counts */
  systemSubtypes: Record<string, number>
  warnings: ParseWarning[]
  /** ms spent parsing */
  parseMs: number
  bytes: number
}

export interface Session {
  meta: SessionMeta
  turns: Turn[]
  messages: Message[]
  toolCalls: ToolCall[]
  agents: AgentRun[]
  skills: SkillInvocation[]
  hooks: HookRun[]
  compactions: CompactionEvent[]
  usageEvents: UsageEvent[]
  /** other notable events (api errors, interruptions, pr links, scheduled wakeups) */
  events: SessionEvent[]
  parseReport: ParseReport
}

export interface SessionEvent {
  kind: 'api_error' | 'interrupt' | 'pr_link' | 'scheduled_fire' | 'away_summary' | 'permission_prompt' | 'plan_mode' | 'model_fallback' | 'other'
  ts?: number
  turnIndex: number
  agentId?: string
  label: string
  detail?: string
}

export function emptyUsage(): Usage {
  return { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cacheWrite5m: 0, cacheWrite1h: 0, webSearchRequests: 0, webFetchRequests: 0 }
}

export function addUsage(a: Usage, b: Usage): Usage {
  return {
    input: a.input + b.input,
    output: a.output + b.output,
    cacheRead: a.cacheRead + b.cacheRead,
    cacheWrite: a.cacheWrite + b.cacheWrite,
    cacheWrite5m: a.cacheWrite5m + b.cacheWrite5m,
    cacheWrite1h: a.cacheWrite1h + b.cacheWrite1h,
    webSearchRequests: a.webSearchRequests + b.webSearchRequests,
    webFetchRequests: a.webFetchRequests + b.webFetchRequests,
    serviceTier: a.serviceTier ?? b.serviceTier,
    speed: a.speed ?? b.speed,
    inferenceGeo: a.inferenceGeo ?? b.inferenceGeo,
  }
}

export function usageTotal(u: Usage): number {
  return u.input + u.output + u.cacheRead + u.cacheWrite
}
