// GENERATED by scripts/build.mjs from src/god. Do not edit.

// src/god/copy.ts
var GOD_COMMAND_DESCRIPTION = "Show the live Claude Code sessions of this machine in one pane.";
var GOD_NOT_READY = "The god pane is not ready in this build.";

// src/god/register.tsx
function register(on, options) {
  on("session.start", async ($, e, next) => {
    await $.command.register({ name: "god", description: GOD_COMMAND_DESCRIPTION });
    return next(e);
  });
  on("command.run", { command: "god" }, async () => ({ text: GOD_NOT_READY }));
}
export {
  register
};
