// Build: (1) bundle the report client (browser) into a JS string module, (2) bundle the CLI (node) into dist/orangu.js.
// Zero runtime dependencies: everything is inlined.
import { build } from 'esbuild'
import { copyFileSync, mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, rmSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// 1) client bundle -> generated TS module
const clientEntry = join(root, 'src/report/client/main.ts')
let clientJs = ''
if (existsSync(clientEntry)) {
  const r = await build({
    entryPoints: [clientEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    target: ['es2020'],
    platform: 'browser',
    write: false,
    legalComments: 'none',
  })
  clientJs = r.outputFiles[0].text
}
// serve-mode bundle: same source, second entry — this one MAY contain
// fetch/EventSource; the file-mode bundle above must not (offline.test.ts greps it).
const serveEntry = join(root, 'src/report/client/serve-entry.ts')
let serveJs = ''
if (existsSync(serveEntry)) {
  const r = await build({
    entryPoints: [serveEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    target: ['es2020'],
    platform: 'browser',
    write: false,
    legalComments: 'none',
  })
  serveJs = r.outputFiles[0].text
}
// CLIENT_CSS = tokens.css (canonical design tokens, also inlined into the landing) + styles.css
const tokensPath = join(root, 'src/report/client/tokens.css')
const cssPath = join(root, 'src/report/client/styles.css')
const tokensCss = existsSync(tokensPath) ? readFileSync(tokensPath, 'utf8') : ''
const clientCss = tokensCss + (existsSync(cssPath) ? readFileSync(cssPath, 'utf8') : '')
mkdirSync(join(root, 'src/report/generated'), { recursive: true })
writeFileSync(
  join(root, 'src/report/generated/client-bundle.ts'),
  `// GENERATED by scripts/build.mjs. Do not edit.\nexport const CLIENT_JS: string = ${JSON.stringify(clientJs)};\nexport const CLIENT_JS_SERVE: string = ${JSON.stringify(serveJs)};\nexport const CLIENT_CSS: string = ${JSON.stringify(clientCss)};\nexport const BUILD_VERSION: string = ${JSON.stringify(pkg.version)};\n`,
)

// 2) CLI bundle
mkdirSync(join(root, 'dist'), { recursive: true })
await build({
  entryPoints: [join(root, 'src/cli/main.ts')],
  bundle: true,
  platform: 'node',
  target: ['node20'],
  format: 'esm',
  outfile: join(root, 'dist/orangu.js'),
  banner: { js: '#!/usr/bin/env node' },
  define: { __ORANGU_VERSION__: JSON.stringify(pkg.version) },
  legalComments: 'none',
})
// 3) plugin-bundled CLI (offline, shipped inside the plugin so skills call it without npx)
const pluginBin = join(root, 'plugin/bin')
mkdirSync(pluginBin, { recursive: true })
await build({
  entryPoints: [join(root, 'src/cli/main.ts')],
  bundle: true,
  platform: 'node',
  target: ['node20'],
  format: 'esm',
  outfile: join(pluginBin, 'orangu.cli.mjs'),
  define: { __ORANGU_VERSION__: JSON.stringify(pkg.version) },
  legalComments: 'none',
})

// 4) Codex plugin bundle. The installable plugin owns the same offline CLI and brand assets as
// the Claude plugin and landing page; no package fetch is required when a skill invokes it.
const codexPluginRoot = join(root, 'plugins/orangu')
mkdirSync(join(codexPluginRoot, 'bin'), { recursive: true })
mkdirSync(join(codexPluginRoot, 'assets'), { recursive: true })
copyFileSync(join(pluginBin, 'orangu.cli.mjs'), join(codexPluginRoot, 'bin/orangu.cli.mjs'))
copyFileSync(join(root, 'design/brand/favicon-64.png'), join(codexPluginRoot, 'assets/icon.png'))
copyFileSync(join(root, 'design/brand/mascot-main-transparent.png'), join(codexPluginRoot, 'assets/logo.png'))

// 4b) Codex skill mirror. plugin/skills/<n>/ is the single source of truth; the Codex copies under
// plugins/orangu/skills/ (installable) and .agents/skills/ (repo-discovered) are GENERATED from it.
// The only hand-written Codex inputs are plugin/codex/<n>/openai.yaml. Every rule below is
// deterministic and fails closed: a skill that cannot be transformed stops the build.
const CODEX_SKILLS = ['improve', 'apply', 'feedback']
const CLAUDE_SKILLS = ['analyze', 'improve', 'apply', 'harness', 'feedback']
const CLAUDE_FALLBACK = 'If `orangu` is not on PATH, run `node "${CLAUDE_PLUGIN_ROOT}/bin/orangu.cli.mjs"` with the same arguments.'
const CODEX_FALLBACK = 'If `orangu` is not on PATH, resolve paths relative to this `SKILL.md`: try `../../bin/orangu.cli.mjs` for an installed plugin, then `../../../dist/orangu.js` for a source checkout, and run the first file that exists with Node.js 20 or newer. Never fetch a package to continue.'
const CODEX_TARGETS = [join(root, '.agents/skills'), join(codexPluginRoot, 'skills')]

function codexNames(text) {
  let out = text
  for (const name of CLAUDE_SKILLS) out = out.replaceAll(`/orangu:${name}`, `$orangu-${name}`)
  return out
}

function codexSkill(name, claude) {
  if (!claude.startsWith('---\n')) throw new Error(`codex mirror: ${name} has no frontmatter`)
  const end = claude.indexOf('\n---\n', 4)
  if (end === -1) throw new Error(`codex mirror: ${name} has an unterminated frontmatter block`)
  const frontmatter = claude.slice(4, end).split('\n')
    .filter((line) => !line.startsWith('allowed-tools:'))
    .map((line) => (line === `name: ${name}` ? `name: orangu-${name}` : line))
  if (!frontmatter.includes(`name: orangu-${name}`)) throw new Error(`codex mirror: ${name} frontmatter has no matching name:`)
  let body = claude.slice(end + 5)
  if (!body.includes(`# /orangu:${name}`)) throw new Error(`codex mirror: ${name} body has no # /orangu:${name} heading`)
  body = body.replace(`# /orangu:${name}`, `# orangu-${name}`)
  if (!body.includes(CLAUDE_FALLBACK)) throw new Error(`codex mirror: ${name} lacks the canonical CLI fallback sentence`)
  body = body.replaceAll(CLAUDE_FALLBACK, CODEX_FALLBACK)
  const out = `---\n${codexNames(frontmatter.join('\n'))}\n---\n${codexNames(body)}`
  if (out.includes('${CLAUDE_PLUGIN_ROOT}')) throw new Error(`codex mirror: ${name} still references CLAUDE_PLUGIN_ROOT after the transform`)
  if (/\/orangu:/.test(out)) throw new Error(`codex mirror: ${name} still contains a Claude slash command after the transform`)
  return out
}

function mirrorDir(src, dst) {
  mkdirSync(dst, { recursive: true })
  for (const entry of readdirSync(src).sort()) {
    const from = join(src, entry)
    const to = join(dst, entry)
    if (statSync(from).isDirectory()) mirrorDir(from, to)
    else if (entry.endsWith('.md')) {
      const text = codexNames(readFileSync(from, 'utf8'))
      if (text.includes('${CLAUDE_PLUGIN_ROOT}')) throw new Error(`codex mirror: ${from} references CLAUDE_PLUGIN_ROOT`)
      writeFileSync(to, text)
    } else copyFileSync(from, to)
  }
}

for (const target of CODEX_TARGETS) {
  for (const dir of [...CODEX_SKILLS.map((n) => `orangu-${n}`), 'shared']) rmSync(join(target, dir), { recursive: true, force: true })
  mirrorDir(join(root, 'plugin/skills/shared'), join(target, 'shared'))
  for (const name of CODEX_SKILLS) {
    const srcDir = join(root, `plugin/skills/${name}`)
    const dstDir = join(target, `orangu-${name}`)
    mkdirSync(dstDir, { recursive: true })
    writeFileSync(join(dstDir, 'SKILL.md'), codexSkill(name, readFileSync(join(srcDir, 'SKILL.md'), 'utf8')))
    if (existsSync(join(srcDir, 'references'))) mirrorDir(join(srcDir, 'references'), join(dstDir, 'references'))
    mkdirSync(join(dstDir, 'agents'), { recursive: true })
    copyFileSync(join(root, `plugin/codex/${name}/openai.yaml`), join(dstDir, 'agents/openai.yaml'))
  }
}

console.log('built CLI + Claude/Codex plugin bundles (client bundle %d bytes, css %d bytes)', clientJs.length, clientCss.length)

// 5) landing site (opt-in: `node scripts/build.mjs --site`).
// site/index.html is generated from site/index.src.html and committed; regenerate after editing the source,
// tokens.css, the design/brand assets, or the package.json version.
// The 3D triad is authored inline in index.src.html.
function buildSite() {
  const src = readFileSync(join(root, 'site/index.src.html'), 'utf8')
  const pngUri = p => `data:image/png;base64,${readFileSync(join(root, p)).toString('base64')}`
  const out = src
    .replace('<!-- @tokens -->', tokensCss.trim())
    // 320px derivative (2x for the 160px CTA display) — the 720 KB master stays for README/hi-res uses
    .replaceAll('{{mascot:main}}', pngUri('design/brand/mascot-main-320.png'))
    // 96px derivative for the 36px header logo (crisp on 2x displays)
    .replaceAll('{{mascot:logo}}', pngUri('design/brand/mascot-96.png'))
    .replaceAll('{{favicon:32}}', pngUri('design/brand/favicon-32.png'))
    .replaceAll('{{favicon:180}}', pngUri('design/brand/favicon-180.png'))
    .replaceAll('{{version}}', pkg.version)
  for (const left of out.match(/\{\{[^}]+\}\}|<!-- @[a-z]+ -->/g) ?? [])
    throw new Error(`buildSite: unresolved placeholder ${left}`)
  writeFileSync(join(root, 'site/index.html'), out)
  console.log('built site/index.html (%d KB)', Math.round(out.length / 1024))
}

// 6) llms.txt + llms-full.txt (part of --site). site/llms.txt is authored in site/llms.src.txt;
// site/llms-full.txt concatenates three public docs verbatim with relative links made absolute.
// The source list is hard-coded on purpose: nothing under docs/research, docs/plans, docs/runs or
// docs/handoff (gitignored private paths) may ever be globbed into a published file.
const LLMS_FULL_SOURCES = ['README.md', 'docs/USAGE.md', 'docs/DETERMINISM.md']
const GITHUB_BLOB = 'https://github.com/NissanOhana/orangu/blob/main/'

function absolutizeLinks(markdown, sourcePath) {
  const dir = sourcePath.includes('/') ? sourcePath.slice(0, sourcePath.lastIndexOf('/') + 1) : ''
  return markdown.replace(/\]\(((?!https?:|#|mailto:)[^)\s]+)\)/g, (_, target) => {
    const [path, hash = ''] = target.split('#')
    const segments = (dir + path).split('/')
    const resolved = []
    for (const seg of segments) {
      if (seg === '..') resolved.pop()
      else if (seg !== '.' && seg !== '') resolved.push(seg)
    }
    return `](${GITHUB_BLOB}${resolved.join('/')}${hash ? `#${hash}` : ''})`
  })
}

function buildLlmsTxt() {
  const llms = readFileSync(join(root, 'site/llms.src.txt'), 'utf8').replaceAll('{{version}}', pkg.version)
  for (const left of llms.match(/\{\{[^}]+\}\}/g) ?? []) throw new Error(`buildLlmsTxt: unresolved placeholder ${left}`)
  writeFileSync(join(root, 'site/llms.txt'), llms)
  const full =
    `# orangu llms-full.txt\n\n` +
    `orangu ${pkg.version}. This file concatenates ${LLMS_FULL_SOURCES.join(', ')} from the repository, verbatim, ` +
    `with relative links rewritten to ${GITHUB_BLOB}. The short index is llms.txt.\n` +
    LLMS_FULL_SOURCES.map((path) => `\n\n---\n\n# ${path}\n\n${absolutizeLinks(readFileSync(join(root, path), 'utf8').trim(), path)}\n`).join('')
  for (const left of full.match(/\{\{[^}]+\}\}/g) ?? []) throw new Error(`buildLlmsTxt: unresolved placeholder ${left}`)
  writeFileSync(join(root, 'site/llms-full.txt'), full)
  console.log('built site/llms.txt (%d KB) + site/llms-full.txt (%d KB)', Math.round(llms.length / 1024), Math.round(full.length / 1024))
}

if (process.argv.includes('--site')) {
  buildSite()
  buildLlmsTxt()
}
