// Build: (1) bundle the report client (browser) into a JS string module, (2) bundle the CLI (node) into dist/orangu.js.
// Zero runtime dependencies: everything is inlined.
import { build } from 'esbuild'
import { copyFileSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// 1) client bundle -> generated TS module
const clientEntry = join(root, 'src/report/client/main.ts')
let clientJs = ''
if (existsSync(clientEntry)) {
  const r = await build({
    entryPoints: [clientEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    target: ['es2020'],
    platform: 'browser',
    write: false,
    legalComments: 'none',
  })
  clientJs = r.outputFiles[0].text
}
// serve-mode bundle: same source, second entry — this one MAY contain
// fetch/EventSource; the file-mode bundle above must not (offline.test.ts greps it).
const serveEntry = join(root, 'src/report/client/serve-entry.ts')
let serveJs = ''
if (existsSync(serveEntry)) {
  const r = await build({
    entryPoints: [serveEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    target: ['es2020'],
    platform: 'browser',
    write: false,
    legalComments: 'none',
  })
  serveJs = r.outputFiles[0].text
}
// CLIENT_CSS = tokens.css (canonical design tokens, also inlined into the landing) + styles.css
const tokensPath = join(root, 'src/report/client/tokens.css')
const cssPath = join(root, 'src/report/client/styles.css')
const tokensCss = existsSync(tokensPath) ? readFileSync(tokensPath, 'utf8') : ''
const clientCss = tokensCss + (existsSync(cssPath) ? readFileSync(cssPath, 'utf8') : '')
mkdirSync(join(root, 'src/report/generated'), { recursive: true })
writeFileSync(
  join(root, 'src/report/generated/client-bundle.ts'),
  `// GENERATED by scripts/build.mjs. Do not edit.\nexport const CLIENT_JS: string = ${JSON.stringify(clientJs)};\nexport const CLIENT_JS_SERVE: string = ${JSON.stringify(serveJs)};\nexport const CLIENT_CSS: string = ${JSON.stringify(clientCss)};\nexport const BUILD_VERSION: string = ${JSON.stringify(pkg.version)};\n`,
)

// 2) CLI bundle
mkdirSync(join(root, 'dist'), { recursive: true })
await build({
  entryPoints: [join(root, 'src/cli/main.ts')],
  bundle: true,
  platform: 'node',
  target: ['node20'],
  format: 'esm',
  outfile: join(root, 'dist/orangu.js'),
  banner: { js: '#!/usr/bin/env node' },
  define: { __ORANGU_VERSION__: JSON.stringify(pkg.version) },
  legalComments: 'none',
})
// 3) plugin-bundled CLI (offline, shipped inside the plugin so skills call it without npx)
const pluginBin = join(root, 'plugin/bin')
mkdirSync(pluginBin, { recursive: true })
await build({
  entryPoints: [join(root, 'src/cli/main.ts')],
  bundle: true,
  platform: 'node',
  target: ['node20'],
  format: 'esm',
  outfile: join(pluginBin, 'orangu.cli.mjs'),
  define: { __ORANGU_VERSION__: JSON.stringify(pkg.version) },
  legalComments: 'none',
})

// 4) Codex plugin bundle. The installable plugin owns the same offline CLI and brand assets as
// the Claude plugin and landing page; no package fetch is required when a skill invokes it.
const codexPluginRoot = join(root, 'plugins/orangu')
mkdirSync(join(codexPluginRoot, 'bin'), { recursive: true })
mkdirSync(join(codexPluginRoot, 'assets'), { recursive: true })
copyFileSync(join(pluginBin, 'orangu.cli.mjs'), join(codexPluginRoot, 'bin/orangu.cli.mjs'))
copyFileSync(join(root, 'design/brand/favicon-64.png'), join(codexPluginRoot, 'assets/icon.png'))
copyFileSync(join(root, 'design/brand/mascot-main-transparent.png'), join(codexPluginRoot, 'assets/logo.png'))

console.log('built CLI + Claude/Codex plugin bundles (client bundle %d bytes, css %d bytes)', clientJs.length, clientCss.length)

// 5) landing site (opt-in: `node scripts/build.mjs --site`).
// site/index.html is generated from site/index.src.html and committed; regenerate after editing the source,
// tokens.css, the design/brand assets, or the package.json version.
// The 3D triad is authored inline in index.src.html.
if (process.argv.includes('--site')) buildSite()

function buildSite() {
  const src = readFileSync(join(root, 'site/index.src.html'), 'utf8')
  const pngUri = p => `data:image/png;base64,${readFileSync(join(root, p)).toString('base64')}`
  const out = src
    .replace('<!-- @tokens -->', tokensCss.trim())
    // 320px derivative (2x for the 160px CTA display) — the 720 KB master stays for README/hi-res uses
    .replaceAll('{{mascot:main}}', pngUri('design/brand/mascot-main-320.png'))
    // 96px derivative for the 36px header logo (crisp on 2x displays)
    .replaceAll('{{mascot:logo}}', pngUri('design/brand/mascot-96.png'))
    .replaceAll('{{favicon:32}}', pngUri('design/brand/favicon-32.png'))
    .replaceAll('{{favicon:180}}', pngUri('design/brand/favicon-180.png'))
    .replaceAll('{{version}}', pkg.version)
  for (const left of out.match(/\{\{[^}]+\}\}|<!-- @[a-z]+ -->/g) ?? [])
    throw new Error(`buildSite: unresolved placeholder ${left}`)
  writeFileSync(join(root, 'site/index.html'), out)
  console.log('built site/index.html (%d KB)', Math.round(out.length / 1024))
}
